import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TopBar } from "@/components/baseLayout/top-bar";
import { BottomBar } from "@/components/baseLayout/bottom-bar";
import { ThemeProvider } from "@/provider/theme-provider";
// import { AppProvider } from "@/provider/app-provider";
import { Toaster } from "sonner";

import "./globals.css";
import SessionProvider from "@/provider/SessionProvider";

const inter = Inter({
    subsets: ["latin", "cyrillic"], // 必要なサブセットを指定
    weight: ["400", "700"], // 必要なウェイトを指定
});

const baseStyle = "w-screen h-screen flex justify-center items-center bg-background overflow-hidden";
const responsiveStyle = "max-w-3xl w-full h-full  py-[70px]  px-5 overflow-y-scroll hidden-scrollbar";

export const metadata: Metadata = {
    title: "Paymeal",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={inter.className + " " + baseStyle}>
                <SessionProvider>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        {/* <AppProvider> */}
                        <TopBar />
                        <div className={responsiveStyle}>{children}</div>
                        <BottomBar />
                        {/* </AppProvider> */}
                        <Toaster />
                    </ThemeProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
